export const BREAKPOINTS = {
  MOBILE: 768,
} as const

export const TIMINGS = {
  LOADING_DURATION_MS: 7000,
  PAGE_TRANSITION_MS: 200,
  ERROR_ANIMATION_MS: 150,
  DEBOUNCE_MS: 400,
  OTP_COOLDOWN_S: 30,
  POWER_PAGES_INIT_MS: 2000,
} as const
