export { createAdminSchema } from './admin'
export { createOTPSchema } from './otp'
export { createQualificationSchema } from './qualification'
export { createSecuritySchema } from './security'
export { wizardSchema } from './wizard'
export type { WizardSchema } from './wizard'
