import { z } from 'zod'

export const wizardSchema = z.object({
  language: z.enum(['fr', 'en']),
  preadmissionId: z.string(),
  birthDate: z.string(),
  otpCode: z.string(),
  reason: z.string(),
  insurance: z.string(),
  hasEmployer: z.boolean(),
  consentNLPD: z.boolean(),
  consentMarketing: z.boolean(),
  identityCard: z.instanceof(File).nullable(),
  insuranceCard: z.instanceof(File).nullable(),
  identityCardBase64: z.string(),
  identityCardMimeType: z.string(),
  insuranceCardBase64: z.string(),
  insuranceCardMimeType: z.string(),
  firstName: z.string(),
  lastName: z.string(),
  birthDatePersonal: z.string(),
  gender: z.string(),
  nationality: z.string(),
  avsNumber: z.string(),
  street: z.string(),
  npa: z.string(),
  city: z.string(),
  country: z.string(),
  email: z.string(),
  profession: z.string(),
  employerName: z.string(),
  employerAddress: z.string(),
  referringDoctor: z.string(),
  generalPractitioner: z.string(),
  accidentDate: z.string(),
  accidentInsurance: z.string(),
  claimNumber: z.string(),
  basicInsurance: z.string(),
  cardNumber: z.string(),
  policyNumber: z.string(),
  complementaryInsurance: z.string(),
})

export type WizardSchema = z.infer<typeof wizardSchema>
