import type { Language } from '@/types/form'

interface Country {
  code: string
  nameFr: string
  nameEn: string
}

const COUNTRIES: Country[] = [
  { code: 'CH', nameFr: 'Suisse', nameEn: 'Switzerland' },
  { code: 'FR', nameFr: 'France', nameEn: 'France' },
  { code: 'AF', nameFr: 'Afghanistan', nameEn: 'Afghanistan' },
  { code: 'ZA', nameFr: 'Afrique du Sud', nameEn: 'South Africa' },
  { code: 'AL', nameFr: 'Albanie', nameEn: 'Albania' },
  { code: 'DZ', nameFr: 'Algérie', nameEn: 'Algeria' },
  { code: 'DE', nameFr: 'Allemagne', nameEn: 'Germany' },
  { code: 'AD', nameFr: 'Andorre', nameEn: 'Andorra' },
  { code: 'AO', nameFr: 'Angola', nameEn: 'Angola' },
  { code: 'SA', nameFr: 'Arabie saoudite', nameEn: 'Saudi Arabia' },
  { code: 'AR', nameFr: 'Argentine', nameEn: 'Argentina' },
  { code: 'AM', nameFr: 'Arménie', nameEn: 'Armenia' },
  { code: 'AU', nameFr: 'Australie', nameEn: 'Australia' },
  { code: 'AT', nameFr: 'Autriche', nameEn: 'Austria' },
  { code: 'AZ', nameFr: 'Azerbaïdjan', nameEn: 'Azerbaijan' },
  { code: 'BE', nameFr: 'Belgique', nameEn: 'Belgium' },
  { code: 'BJ', nameFr: 'Bénin', nameEn: 'Benin' },
  { code: 'BY', nameFr: 'Biélorussie', nameEn: 'Belarus' },
  { code: 'BO', nameFr: 'Bolivie', nameEn: 'Bolivia' },
  { code: 'BA', nameFr: 'Bosnie-Herzégovine', nameEn: 'Bosnia and Herzegovina' },
  { code: 'BW', nameFr: 'Botswana', nameEn: 'Botswana' },
  { code: 'BR', nameFr: 'Brésil', nameEn: 'Brazil' },
  { code: 'BG', nameFr: 'Bulgarie', nameEn: 'Bulgaria' },
  { code: 'BF', nameFr: 'Burkina Faso', nameEn: 'Burkina Faso' },
  { code: 'BI', nameFr: 'Burundi', nameEn: 'Burundi' },
  { code: 'KH', nameFr: 'Cambodge', nameEn: 'Cambodia' },
  { code: 'CM', nameFr: 'Cameroun', nameEn: 'Cameroon' },
  { code: 'CA', nameFr: 'Canada', nameEn: 'Canada' },
  { code: 'CL', nameFr: 'Chili', nameEn: 'Chile' },
  { code: 'CN', nameFr: 'Chine', nameEn: 'China' },
  { code: 'CY', nameFr: 'Chypre', nameEn: 'Cyprus' },
  { code: 'CO', nameFr: 'Colombie', nameEn: 'Colombia' },
  { code: 'KR', nameFr: 'Corée du Sud', nameEn: 'South Korea' },
  { code: 'CR', nameFr: 'Costa Rica', nameEn: 'Costa Rica' },
  { code: 'CI', nameFr: "Côte d'Ivoire", nameEn: 'Ivory Coast' },
  { code: 'HR', nameFr: 'Croatie', nameEn: 'Croatia' },
  { code: 'CU', nameFr: 'Cuba', nameEn: 'Cuba' },
  { code: 'DK', nameFr: 'Danemark', nameEn: 'Denmark' },
  { code: 'EG', nameFr: 'Égypte', nameEn: 'Egypt' },
  { code: 'AE', nameFr: 'Émirats arabes unis', nameEn: 'United Arab Emirates' },
  { code: 'EC', nameFr: 'Équateur', nameEn: 'Ecuador' },
  { code: 'ES', nameFr: 'Espagne', nameEn: 'Spain' },
  { code: 'EE', nameFr: 'Estonie', nameEn: 'Estonia' },
  { code: 'US', nameFr: 'États-Unis', nameEn: 'United States' },
  { code: 'ET', nameFr: 'Éthiopie', nameEn: 'Ethiopia' },
  { code: 'FI', nameFr: 'Finlande', nameEn: 'Finland' },
  { code: 'GA', nameFr: 'Gabon', nameEn: 'Gabon' },
  { code: 'GE', nameFr: 'Géorgie', nameEn: 'Georgia' },
  { code: 'GH', nameFr: 'Ghana', nameEn: 'Ghana' },
  { code: 'GR', nameFr: 'Grèce', nameEn: 'Greece' },
  { code: 'GT', nameFr: 'Guatemala', nameEn: 'Guatemala' },
  { code: 'GN', nameFr: 'Guinée', nameEn: 'Guinea' },
  { code: 'HT', nameFr: 'Haïti', nameEn: 'Haiti' },
  { code: 'HN', nameFr: 'Honduras', nameEn: 'Honduras' },
  { code: 'HU', nameFr: 'Hongrie', nameEn: 'Hungary' },
  { code: 'IN', nameFr: 'Inde', nameEn: 'India' },
  { code: 'ID', nameFr: 'Indonésie', nameEn: 'Indonesia' },
  { code: 'IQ', nameFr: 'Irak', nameEn: 'Iraq' },
  { code: 'IR', nameFr: 'Iran', nameEn: 'Iran' },
  { code: 'IE', nameFr: 'Irlande', nameEn: 'Ireland' },
  { code: 'IS', nameFr: 'Islande', nameEn: 'Iceland' },
  { code: 'IL', nameFr: 'Israël', nameEn: 'Israel' },
  { code: 'IT', nameFr: 'Italie', nameEn: 'Italy' },
  { code: 'JM', nameFr: 'Jamaïque', nameEn: 'Jamaica' },
  { code: 'JP', nameFr: 'Japon', nameEn: 'Japan' },
  { code: 'JO', nameFr: 'Jordanie', nameEn: 'Jordan' },
  { code: 'KZ', nameFr: 'Kazakhstan', nameEn: 'Kazakhstan' },
  { code: 'KE', nameFr: 'Kenya', nameEn: 'Kenya' },
  { code: 'XK', nameFr: 'Kosovo', nameEn: 'Kosovo' },
  { code: 'KW', nameFr: 'Koweït', nameEn: 'Kuwait' },
  { code: 'LV', nameFr: 'Lettonie', nameEn: 'Latvia' },
  { code: 'LB', nameFr: 'Liban', nameEn: 'Lebanon' },
  { code: 'LR', nameFr: 'Liberia', nameEn: 'Liberia' },
  { code: 'LY', nameFr: 'Libye', nameEn: 'Libya' },
  { code: 'LI', nameFr: 'Liechtenstein', nameEn: 'Liechtenstein' },
  { code: 'LT', nameFr: 'Lituanie', nameEn: 'Lithuania' },
  { code: 'LU', nameFr: 'Luxembourg', nameEn: 'Luxembourg' },
  { code: 'MK', nameFr: 'Macédoine du Nord', nameEn: 'North Macedonia' },
  { code: 'MG', nameFr: 'Madagascar', nameEn: 'Madagascar' },
  { code: 'MY', nameFr: 'Malaisie', nameEn: 'Malaysia' },
  { code: 'ML', nameFr: 'Mali', nameEn: 'Mali' },
  { code: 'MT', nameFr: 'Malte', nameEn: 'Malta' },
  { code: 'MA', nameFr: 'Maroc', nameEn: 'Morocco' },
  { code: 'MX', nameFr: 'Mexique', nameEn: 'Mexico' },
  { code: 'MD', nameFr: 'Moldavie', nameEn: 'Moldova' },
  { code: 'MC', nameFr: 'Monaco', nameEn: 'Monaco' },
  { code: 'MN', nameFr: 'Mongolie', nameEn: 'Mongolia' },
  { code: 'ME', nameFr: 'Monténégro', nameEn: 'Montenegro' },
  { code: 'MZ', nameFr: 'Mozambique', nameEn: 'Mozambique' },
  { code: 'MM', nameFr: 'Myanmar', nameEn: 'Myanmar' },
  { code: 'NA', nameFr: 'Namibie', nameEn: 'Namibia' },
  { code: 'NP', nameFr: 'Népal', nameEn: 'Nepal' },
  { code: 'NI', nameFr: 'Nicaragua', nameEn: 'Nicaragua' },
  { code: 'NE', nameFr: 'Niger', nameEn: 'Niger' },
  { code: 'NG', nameFr: 'Nigeria', nameEn: 'Nigeria' },
  { code: 'NO', nameFr: 'Norvège', nameEn: 'Norway' },
  { code: 'NZ', nameFr: 'Nouvelle-Zélande', nameEn: 'New Zealand' },
  { code: 'OM', nameFr: 'Oman', nameEn: 'Oman' },
  { code: 'UG', nameFr: 'Ouganda', nameEn: 'Uganda' },
  { code: 'UZ', nameFr: 'Ouzbékistan', nameEn: 'Uzbekistan' },
  { code: 'PK', nameFr: 'Pakistan', nameEn: 'Pakistan' },
  { code: 'PA', nameFr: 'Panama', nameEn: 'Panama' },
  { code: 'PY', nameFr: 'Paraguay', nameEn: 'Paraguay' },
  { code: 'NL', nameFr: 'Pays-Bas', nameEn: 'Netherlands' },
  { code: 'PE', nameFr: 'Pérou', nameEn: 'Peru' },
  { code: 'PH', nameFr: 'Philippines', nameEn: 'Philippines' },
  { code: 'PL', nameFr: 'Pologne', nameEn: 'Poland' },
  { code: 'PT', nameFr: 'Portugal', nameEn: 'Portugal' },
  { code: 'QA', nameFr: 'Qatar', nameEn: 'Qatar' },
  { code: 'CZ', nameFr: 'République tchèque', nameEn: 'Czech Republic' },
  { code: 'RO', nameFr: 'Roumanie', nameEn: 'Romania' },
  { code: 'GB', nameFr: 'Royaume-Uni', nameEn: 'United Kingdom' },
  { code: 'RU', nameFr: 'Russie', nameEn: 'Russia' },
  { code: 'RW', nameFr: 'Rwanda', nameEn: 'Rwanda' },
  { code: 'SN', nameFr: 'Sénégal', nameEn: 'Senegal' },
  { code: 'RS', nameFr: 'Serbie', nameEn: 'Serbia' },
  { code: 'SG', nameFr: 'Singapour', nameEn: 'Singapore' },
  { code: 'SK', nameFr: 'Slovaquie', nameEn: 'Slovakia' },
  { code: 'SI', nameFr: 'Slovénie', nameEn: 'Slovenia' },
  { code: 'SO', nameFr: 'Somalie', nameEn: 'Somalia' },
  { code: 'SD', nameFr: 'Soudan', nameEn: 'Sudan' },
  { code: 'LK', nameFr: 'Sri Lanka', nameEn: 'Sri Lanka' },
  { code: 'SE', nameFr: 'Suède', nameEn: 'Sweden' },
  { code: 'SY', nameFr: 'Syrie', nameEn: 'Syria' },
  { code: 'TZ', nameFr: 'Tanzanie', nameEn: 'Tanzania' },
  { code: 'TD', nameFr: 'Tchad', nameEn: 'Chad' },
  { code: 'TH', nameFr: 'Thaïlande', nameEn: 'Thailand' },
  { code: 'TG', nameFr: 'Togo', nameEn: 'Togo' },
  { code: 'TN', nameFr: 'Tunisie', nameEn: 'Tunisia' },
  { code: 'TR', nameFr: 'Turquie', nameEn: 'Turkey' },
  { code: 'UA', nameFr: 'Ukraine', nameEn: 'Ukraine' },
  { code: 'UY', nameFr: 'Uruguay', nameEn: 'Uruguay' },
  { code: 'VE', nameFr: 'Venezuela', nameEn: 'Venezuela' },
  { code: 'VN', nameFr: 'Viêt Nam', nameEn: 'Vietnam' },
  { code: 'YE', nameFr: 'Yémen', nameEn: 'Yemen' },
  { code: 'ZM', nameFr: 'Zambie', nameEn: 'Zambia' },
  { code: 'ZW', nameFr: 'Zimbabwe', nameEn: 'Zimbabwe' },
]

export function getCountries(language: Language): { code: string; name: string }[] {
  const priority = ['CH', 'FR']
  const priorityCountries = COUNTRIES.filter((c) => priority.includes(c.code))
  const otherCountries = COUNTRIES.filter((c) => !priority.includes(c.code))
  const getName = (c: Country) => (language === 'fr' ? c.nameFr : c.nameEn)
  return [
    ...priorityCountries.map((c) => ({ code: c.code, name: getName(c) })),
    ...otherCountries.map((c) => ({ code: c.code, name: getName(c) })).sort((a, b) => a.name.localeCompare(b.name)),
  ]
}

export function getCountryNameByCode(isoCode: string, language: Language): string {
  const country = COUNTRIES.find((c) => c.code === isoCode.toUpperCase())
  if (!country) return isoCode
  return language === 'fr' ? country.nameFr : country.nameEn
}
